### ISSUE TITLE
Typing latency doubled by this extension

### ISSUE THREAD

**Issue by mauro3** [SebastianZaha/vscode-emacs-friendly#20] opened 2017-08-09 07:58 UTC
I'm currently trying out VScode to see whether it could (partially) replace emacs.  Naturally I was interested to compare typing latency (time between key-press and character showing on screen), see [here](https://pavelfatin.com/typing-with-pleasure/).  I used typometer as in that blog post and found that on my system enabling this extension doubled the latency.  

Here a screenshot with all my extension disabled:
![vscode-emacs](https://user-images.githubusercontent.com/4098145/29110874-79183d24-7ce8-11e7-81ad-5be1321be0f2.png)
Shows average latency of 16.9ms, max 33.1ms and std-dev 2.8ms.

Here with all my extension disabled except vscode-emacs-friendly:
![vscode-no-emacs](https://user-images.githubusercontent.com/4098145/29110875-791969ce-7ce8-11e7-81a1-51fed4ff9eac.png)
Shows average latency of 32.7ms, max 49.8ms and std-dev 4.1ms.

Is there anything which could be done about this?

Edit: See also https://github.com/Microsoft/vscode/issues/27378

**Comment by mauro3** [comment] 2017-08-09 08:14
As a side note: below the results for my Emacs setup (i.e. with my .emacs loaded):

![emacs](https://user-images.githubusercontent.com/4098145/29111621-4a126dda-7ceb-11e7-9983-05ae7706c929.png)
Shows average latency of 5.9ms, max 65ms (just one spike though).

**Comment by SebastianZaha** [comment] 2017-08-09 08:14
Thanks for the report, seems like this should definitely be addressed. I will install typometer and try to find the cause.

**Comment by SebastianZaha** [comment] 2017-08-11 09:15
I have found a big culprit here, the old extension had a beginning of an implementation of a register mode which was intercepting typing events. I have removed it as it was causing it too much latency, we'll have to find another implementation.

Could you please re-do the tests on your machine? On mine this got it down 30%.

**Comment by SebastianZaha** [comment] 2017-08-11 09:16
After updating to 0.8.0 I  mean :)

**Comment by mauro3** [comment] 2017-08-11 09:20
Cheers! But how do I install it?  I know how to install from VSIX. If from VSIX, how do I make one?

**Comment by SebastianZaha** [comment] 2017-08-11 09:23
It's published, so from your extensions tab, click "check for updates" and reload the window afterwards.

Sometimes it takes a bit for a new version to show up, if you do not see an update available, perhaps try again in 30 mins or so...

**Comment by mauro3** [comment] 2017-08-11 09:33
Ok, got it. Yes it is better, thanks for looking into this!

The average is now 23ms, here the graph:
![vscode-emacs-mode](https://user-images.githubusercontent.com/4098145/29207988-81455cec-7e88-11e7-84f9-c16c15d36c75.png)

However, it looks like it is bouncing back and forth between the base value 16ms and slow 33ms.  I would think an even 23ms would be better.

**Comment by SebastianZaha** [comment] 2017-08-11 09:38
I am not sure why but Typometer does not finish when I run it, it always times out with "cannot detect char" at some point. This is on ubuntu / gnome. I tried with osx too and there it seems sometimes it finishes but often does not. 

What system are you running it on?

**Comment by mauro3** [comment] 2017-08-11 09:50
Yes, I have that problem with VScode too (not with emacs though).  To fix zoom in a lot.  Also, I think you need at least one other line which is wider than the screen to make it work.  Also, it's recommended to use a non-block cursor but I didn't see any difference there.

I run ArchLinux with xmonad window manager.

**Comment by SebastianZaha** [comment] 2017-08-11 11:06
It does work when zoomed in and with one line larger than the screen indeed. But runs vary a lot between them, even without any extensions, there are weird spikes, and I don't see a clear indication that enabling the extension is making it worse... Not sure what is going on my system.

**Comment by mauro3** [comment] 2017-08-11 11:17
Have you tried it with emacs or another editor? Do you have some funky window manager like Compiz? Docs recommend to close all other applications, but I didn't and it worked fine.

**Comment by SebastianZaha** [comment] 2017-08-11 11:22
Yes @ compiz, i think it's in the default ubuntu desktop instalation, I did not change anything this time :)

I will try on OSX as well again, with the zoom in trick. 

But the bouncing graph is reproducible for you, right? And does it go away when disabling the extension?

**Comment by mauro3** [comment] 2017-08-11 11:32
Yes, it says Compiz adds 10ms: https://pavelfatin.com/typometer/

Looks pretty good at the moment with less spikes and average down to 15ms, which is about what I get without extensions:
![v2](https://user-images.githubusercontent.com/4098145/29211419-4a8a08f4-7e99-11e7-86b5-1db391969382.png)
So, no, not super reproducible, but I think that is expected.

**Comment by SebastianZaha** [comment] 2017-08-11 11:35
Yep, understood. Thanks for all the clarifications, much appreciated, I'm glad I removed that latency-inducing legacy stuff :) !

I'll close this for now, but will remain subscribed to the vscode issue you opened and wait for some devs to chime in.

**Closed by SebastianZaha** 2017-08-11 11:35 UTC

**Comment by laustbn** [comment] 2017-08-11 12:19
The `C-l`/recenter addition from me (that already made it in, thanks!) listens for the `onDidChangeTextEditorSelection` event which triggers every time the cursor position changes. Even though the event handler only sets a flag, I suppose it could contribute to the spikes.

Personally the lag in the old release wasn't noticeable or bothersome to me. Growing up using remote terminals over a modem may have left a mark... :)
